pom.xml
src/test/java/com/nhnacademy/booklay/server/repository/MemberRepositoryTest.java

- 소나큐브 TC 0% 버그 해결
- jacoco dependency 추가
- maven lifecycle test error 해결 
- -> MemberRepositoryTest에서 autoincrement로 인한 에러. -> 해결

fix: add jacoco dependency and fix member test failure

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/CouponAdminController.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminService.java

coupon crud에 필요한 controller, service 생성.

feat: coupon crud 작성 #124

---

src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
src/main/java/com/nhnacademy/booklay/server/dto/member/MemberDto.java
src/main/java/com/nhnacademy/booklay/server/repository/MemberRepository.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java

feat:member read 기능 추가 #23

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/CouponAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponCURequest.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponCreateRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponDetailRetrieveResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponRetrieveResponse.java
src/main/java/com/nhnacademy/booklay/server/repository/coupon/CouponRepository.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminService.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
src/test/java/com/nhnacademy/booklay/server/repository/CouponRepositoryTest.java
src/test/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImplTest.java

coupon admin service test 진행하고 있습니다.

feat: coupon crud

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/CategoryAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/PageResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/category/request/CategoryCreateRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/category/response/CategoryResponse.java
src/main/java/com/nhnacademy/booklay/server/entity/Category.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryService.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/admin/CategoryAdminControllerTest.java

RestTemplate 요청에 응답할 수 있도록 일부 코드 수정

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/coupon/CouponAdminController.java
src/main/java/com/nhnacademy/booklay/server/controller/admin/coupon/CouponTypeAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponCreateRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponIssueRequest.java
src/main/java/com/nhnacademy/booklay/server/entity/OrderCoupon.java
src/main/java/com/nhnacademy/booklay/server/entity/ProductCoupon.java
src/main/java/com/nhnacademy/booklay/server/repository/coupon/OrderCouponRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/coupon/ProductCouponRepository.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminService.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/admin/coupon/CouponAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/controller/admin/coupon/CouponTypeAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
src/test/java/com/nhnacademy/booklay/server/repository/coupon/CouponTypeRepositoryTest.java
src/test/java/com/nhnacademy/booklay/server/repository/coupon/OrderCouponRepositoryTest.java
src/test/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImplTest.java

관리자가 회원에게 주문쿠폰(order_coupon) 발급 작성했습니다.
coupon Type controller, service, repository 테스트 했습니다.

feat: order coupon

---

src/main/java/com/nhnacademy/booklay/server/controller/member/MemberAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberGradeRetrieveResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberRetrieveResponse.java
src/main/java/com/nhnacademy/booklay/server/repository/member/MemberGradeRepository.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/member/MemberAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/controller/member/MemberControllerTest.java
src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java

member authority, grade 생성, 삭제 메소드 구현, 관련 tc 작성

Feature/member grade/authority

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/coupon/CouponAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/CouponCreateRequest.java
src/main/java/com/nhnacademy/booklay/server/entity/Coupon.java
src/main/java/com/nhnacademy/booklay/server/entity/Image.java
src/main/java/com/nhnacademy/booklay/server/entity/Member.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/admin/coupon/CouponAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
src/test/java/com/nhnacademy/booklay/server/repository/coupon/OrderCouponRepositoryTest.java
src/test/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImplTest.java

fix: coupon 생성 수정

---

src/main/java/com/nhnacademy/booklay/server/entity/Authority.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/member/MemberAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java

fix: memberId 중복체크 기능 구현

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/product/AuthorAdminController.java
src/main/java/com/nhnacademy/booklay/server/controller/admin/product/ProductAdminController.java
src/main/java/com/nhnacademy/booklay/server/controller/admin/product/TagAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/product/author/response/RetrieveAuthorResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/request/CreateProductBookRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/product/tag/request/CreateDeleteTagProductRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/product/tag/response/TagProductResponse.java
src/main/java/com/nhnacademy/booklay/server/entity/Image.java
src/main/java/com/nhnacademy/booklay/server/entity/ProductTag.java
src/main/java/com/nhnacademy/booklay/server/repository/CartRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/product/CategoryProductRepository.java
src/main/java/com/nhnacademy/booklay/server/service/product/TagService.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/TagServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/dummy/DummyCart.java
src/test/java/com/nhnacademy/booklay/server/dummy/DummyNum3.java
src/test/java/com/nhnacademy/booklay/server/service/product/ProductAuthorServiceTest.java
src/test/java/com/nhnacademy/booklay/server/service/product/ProductServiceTest.java

상품에 태그 등록/삭제, 상품 등록 구현

---

src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/logback-dev.xml
src/main/resources/logback-prod.xml

yml 파일 수정, xml 파일 추가하였습니다
/${HOME}/Documents/booklay/shop/${profile}_${DATE}.log

feat: logback.xml 적용

---

src/main/java/com/nhnacademy/booklay/server/controller/mypage/PointHistoryController.java
src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryService.java
src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryTest.java

member point 부분 리스트 조회 구현, 사용자끼리 선물하기 마무리

feat: 포인트 조회 구현, 포인트 선물하기 보완

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/category/CategoryAdminController.java
src/main/java/com/nhnacademy/booklay/server/dto/category/request/CategoryCreateRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/category/request/CategoryUpdateRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/category/response/CategoryStep.java
src/main/java/com/nhnacademy/booklay/server/dto/category/response/CategoryStepResponse.java
src/main/java/com/nhnacademy/booklay/server/entity/Category.java
src/main/java/com/nhnacademy/booklay/server/repository/CategoryRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/category/CategoryRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/category/CategoryRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/category/impl/CategoryRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryService.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java
src/main/resources/logback-dev.xml
src/main/resources/logback-prod.xml
src/test/java/com/nhnacademy/booklay/server/controller/admin/CategoryAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/repository/CategoryRepositoryTest.java
src/test/java/com/nhnacademy/booklay/server/service/category/CategoryServiceTest.java
src/test/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImplTest.java
src/test/java/com/nhnacademy/booklay/server/service/product/ProductServiceTest.java
src/test/resources/data.sql

2단 카테고리 메뉴 추가를 위한 base 컨트롤러 추가

---

src/main/java/com/nhnacademy/booklay/server/controller/storage/StorageController.java
src/main/resources/application-prod.yml

upload 했을 때, 로직을 fileSerive에서 처리하고 ObjectFile 반환하게 변경.

fix: StorageController

---

src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberLoginResponse.java
src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
src/main/resources/application-prod.yml

email을 통해 로그인한 사용자를 조회하기 위한 API 작성

email을 통한 멤버 조회 구현

---

src/main/java/com/nhnacademy/booklay/server/service/cart/RedisCartServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java

ProductServiceImpl

---

src/main/java/com/nhnacademy/booklay/server/controller/WebControllerAdvice.java
src/main/java/com/nhnacademy/booklay/server/controller/search/SearchController.java
src/main/java/com/nhnacademy/booklay/server/dto/product/author/AuthorsInProduct.java
src/main/java/com/nhnacademy/booklay/server/dto/product/author/response/RetrieveAuthorResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/RetrieveProductBookResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/RetrieveProductResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/RetrieveProductSubscribeResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/tag/response/RetrieveTagResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/search/request/SearchRequest.java
src/main/java/com/nhnacademy/booklay/server/entity/ProductDetail.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/product/impl/ProductRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImplTest.java

Query Dsl 적용 및 DTO 수정

---

src/main/java/com/nhnacademy/booklay/server/controller/search/SearchController.java
src/main/java/com/nhnacademy/booklay/server/dto/product/author/AuthorsInProduct.java

UI 개선 작업 중 발견한 오류 수정

---

src/main/java/com/nhnacademy/booklay/server/constant/Roles.java
src/main/java/com/nhnacademy/booklay/server/controller/auth/AuthController.java
src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberLoginResponse.java
src/main/java/com/nhnacademy/booklay/server/entity/Member.java
src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java

Github 소셜 로그인에 필요한 API 구현

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/product/ProductAdminController.java
src/main/java/com/nhnacademy/booklay/server/controller/search/SearchController.java
src/main/java/com/nhnacademy/booklay/server/dto/product/author/AuthorsInProduct.java
src/main/java/com/nhnacademy/booklay/server/dto/product/category/CategoriesInProduct.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/ProductAllInOneResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/ProductDetailResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/ProductResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/response/SubscribeResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/product/tag/TagsInProduct.java
src/main/java/com/nhnacademy/booklay/server/dto/search/request/SearchRequest.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/product/impl/ProductRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/ProductService.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/search/SearchService.java
src/main/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImplTest.java

상품 DTO 수정에 따른 리턴 타입 변경

---

src/main/java/com/nhnacademy/booklay/server/BooklayShopApplication.java
src/main/java/com/nhnacademy/booklay/server/aspect/MemberAspect.java
src/main/java/com/nhnacademy/booklay/server/config/WebConfig.java
src/main/java/com/nhnacademy/booklay/server/dto/common/MemberInfo.java
src/main/java/com/nhnacademy/booklay/server/filter/ContentCachingRequestWrapperFilter.java

MemberInfo AOP 추가

---

src/main/java/com/nhnacademy/booklay/server/entity/CategoryProduct.java
src/main/java/com/nhnacademy/booklay/server/repository/product/CategoryProductRepository.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryProductService.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryProductServiceImpl.java

CategoryProductService

---

src/main/java/com/nhnacademy/booklay/server/controller/coupon/CouponZoneController.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/message/CouponIssueRequestMessage.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/message/CouponIssueResponseMessage.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/response/CouponIssueResponse.java
src/main/java/com/nhnacademy/booklay/server/dto/coupon/response/CouponMemberResponse.java
src/main/java/com/nhnacademy/booklay/server/service/kafka/CouponZoneIssueService.java
src/main/resources/application-dev.yml

쿠폰 발급 구현.
발급 요청을 message Queue 추가하고,
응답을 보낼 사용자 식별자(requestId) 를 레디스에 저장함.

feat: coupon zone issue

---

src/main/java/com/nhnacademy/booklay/server/service/product/ProductService.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java

fix: error fix

---

src/main/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/search/SearchControllerTest.java
src/test/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImplTest.java

검색 서비스와 컨트롤러 테스트 추가하였습니다.

---

src/main/java/com/nhnacademy/booklay/server/controller/search/SearchController.java
src/main/java/com/nhnacademy/booklay/server/dto/search/request/SearchIdRequest.java
src/main/java/com/nhnacademy/booklay/server/service/search/SearchService.java
src/main/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/controller/search/SearchControllerTest.java
src/test/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImplTest.java

상품 추천 및 작가 태그 번호 검색 추가

---

src/main/java/com/nhnacademy/booklay/server/config/KafkaConfig.java
src/main/java/com/nhnacademy/booklay/server/service/kafka/CouponZoneIssueService.java

feat: coupon member

---

src/main/java/com/nhnacademy/booklay/server/entity/Member.java

회원 soft delete 시 unique 조건에 따른 deleted + pk 값 설정

fix: unique 조건에 따른 deleted에 pk 추가

---

src/main/java/com/nhnacademy/booklay/server/dto/member/response/MemberRetrieveResponse.java
src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryImpl.java

- 버그있을수도 있음
- 버그날 경우 화이팅..
- 롤백해보고.. aop 잘 수정바람..

memberinfo AOP 권한, 등급 추가

---

src/main/java/com/nhnacademy/booklay/server/controller/coupon/CouponZoneController.java
src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
src/main/resources/application-dev.yml

회원가입후에 회원가입 쿠폰 요청을 보내기 위하여,
회원 가입 후에 사용자의 id를 반환하도록 수정했습니다.

fix: 회원가입 후 사용자의 id 반환하도록 수정

---

src/main/java/com/nhnacademy/booklay/server/config/ElasticSearchConfig.java
src/main/java/com/nhnacademy/booklay/server/controller/review/ReviewController.java
src/main/java/com/nhnacademy/booklay/server/dto/review/request/ReviewCreateRequest.java
src/main/java/com/nhnacademy/booklay/server/dto/review/response/RetrieveReviewResponse.java
src/main/java/com/nhnacademy/booklay/server/entity/Review.java
src/main/java/com/nhnacademy/booklay/server/exception/controller/CreateFailedException.java
src/main/java/com/nhnacademy/booklay/server/repository/ReviewRepository.java
src/main/java/com/nhnacademy/booklay/server/service/review/ReviewService.java
src/main/resources/application-dev.yml

리뷰 작성 등록 및 포인트 적립, 삭제 추가하였습니다

---

src/main/java/com/nhnacademy/booklay/server/entity/document/ProductDocument.java
src/main/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImpl.java
src/test/resources/data.sql

fix: 최근 신간 추천 정렬 수정

---

src/main/java/com/nhnacademy/booklay/server/config/ElasticSearchConfig.java
src/main/java/com/nhnacademy/booklay/server/controller/review/ReviewController.java
src/main/java/com/nhnacademy/booklay/server/dto/search/response/SearchPageResponse.java
src/main/java/com/nhnacademy/booklay/server/repository/ReviewRepository.java
src/main/java/com/nhnacademy/booklay/server/service/review/ReviewService.java
src/main/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImpl.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/test/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImplTest.java

상품 리뷰 노출 정보 수정 및 엘라스틱 서치 테스트 수정

---

src/test/java/com/nhnacademy/booklay/server/repository/delivery/DeliveryDestinationRepositoryTest.java

test: test 수정

---

src/main/java/com/nhnacademy/booklay/server/config/ElasticSearchConfig.java
src/main/java/com/nhnacademy/booklay/server/controller/product/ProductController.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductRepositoryCustom.java
src/main/java/com/nhnacademy/booklay/server/repository/product/impl/ProductRepositoryImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/ProductService.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/search/impl/SearchServiceImpl.java

fix: 상품 노출 버그 수정

---

src/test/java/com/nhnacademy/booklay/server/repository/BlockedMemberDetailRepositoryTest.java

Test/delivery detail/sleepadd

---

src/main/java/com/nhnacademy/booklay/server/controller/product/ProductController.java
src/main/java/com/nhnacademy/booklay/server/repository/product/CategoryProductRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductAuthorRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductRepository.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductTagRepository.java
src/main/java/com/nhnacademy/booklay/server/service/product/ProductService.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java

fix: 상품 노출 로직 수정

---

src/main/java/com/nhnacademy/booklay/server/controller/review/ReviewController.java
src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/utils/Grade.java

fix: 리뷰 response Entity 수정 및 멤버 등급 저장 변경

---

pom.xml
src/main/java/com/nhnacademy/booklay/server/config/ElasticSearchConfig.java
src/main/java/com/nhnacademy/booklay/server/repository/product/ProductRepository.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/service/category/CategoryServiceTest.java
src/test/java/com/nhnacademy/booklay/server/service/product/impl/ProductServiceImplTest.java

소나린트 버그 픽스

---

src/main/java/com/nhnacademy/booklay/server/controller/admin/category/CategoryAdminController.java
src/main/java/com/nhnacademy/booklay/server/repository/category/CategoryRepository.java
src/main/java/com/nhnacademy/booklay/server/service/category/CategoryServiceImpl.java

fix: 카테고리 수정시 쿠폰 정보 변경 추가

---

src/main/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationServiceImpl.java
src/main/java/com/nhnacademy/booklay/server/service/mypage/impl/PointHistoryServiceImpl.java
src/test/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationServiceImplTest.java
src/test/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryServiceImplTest.java

test: test 작성

---

pom.xml

chore: 소나큐브 제외 패키지 추가

---

pom.xml
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/test/java/com/nhnacademy/booklay/server/controller/admin/category/CategoryAdminControllerTest.java
src/test/resources/application-test.yml

chore: rest doc 관련 설정 추가

---

src/asciidoc/admin_categories.adoc
src/asciidoc/adoc_README.md
src/asciidoc/index.adoc

docs : rest Docs adoc 파일 작성법 추가

---

.github/workflows/ci.yml
.github/workflows/maven.yml

feat: workflow jobs 분리

---

src/asciidoc/admin/category/admin_category.adoc
src/asciidoc/admin/member/admin_member.adoc
src/asciidoc/auth/member.adoc
src/asciidoc/cart/cart.adoc
src/asciidoc/member.adoc
src/asciidoc/member/member.adoc
src/asciidoc/order/order.adoc
src/main/java/com/nhnacademy/booklay/server/dto/order/payment/StorageRequest.java
src/test/java/com/nhnacademy/booklay/server/controller/admin/category/CategoryAdminControllerTest.java
src/test/java/com/nhnacademy/booklay/server/controller/cart/CartControllerTest.java
src/test/java/com/nhnacademy/booklay/server/controller/member/MemberControllerTest.java
src/test/java/com/nhnacademy/booklay/server/controller/order/OrderControllerTest.java
src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java

feat: api 문서 작성

---

.github/workflows/maven.yml

feat: git action 수정

---

src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java
src/test/java/com/nhnacademy/booklay/server/service/order/ComplexOrderServiceImplTest.java
src/test/java/com/nhnacademy/booklay/server/service/review/ReviewServiceTest.java

test: complex order service 테스트
